name: 📦 Release Packages

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'apps/**'

jobs:
  test:
    name: 🧪 Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: 📦 Install dependencies
        run: bun install
      - name: 🔍 Run type checking
        run: bun run typecheck
      - name: 🔬 Run linting
        run: bun run lint
      - name: 🧪 Run unit tests
        run: bun run test
    
  create-release:
    name: 📦 Create Release  
    needs: [test]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: 📦 Install dependencies
        run: bun install
      - name: 🏗️ Build packages
        run: bun turbo build --filter=made2web --filter=@made2web/react-email
      - name: 🔖 Create and publish versions
        uses: changesets/action@master
        with:
          version: bun run changeset version
          commit: "chore: update versions"
          title: "chore: update versions"
          publish: bun run changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          